// This file was automatically generated by VS extension Windows Machine Learning Code Generator v3
// from model file version-RFB-320.onnx
// Warning: This file may get overwritten if you add add an onnx file with the same name
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Windows.Media;
using Windows.Storage;
using Windows.Storage.Streams;
using Windows.AI.MachineLearning;
namespace FaceRecognitionUWP
{
    
    public sealed class Input
    {
        public TensorFloat input; // shape(1,3,240,320)
    }
    
    public sealed class Output
    {
        public TensorFloat scores; // shape(1,4420,2)
        public TensorFloat boxes; // shape(1,4420,4)
    }
    
    public sealed class Model
    {
        private LearningModel model;
        private LearningModelSession session;
        private LearningModelBinding binding;
        public static async Task<Model> CreateFromStreamAsync(IRandomAccessStreamReference stream)
        {
            Model learningModel = new Model();
            learningModel.model = await LearningModel.LoadFromStreamAsync(stream);
            learningModel.session = new LearningModelSession(learningModel.model);
            learningModel.binding = new LearningModelBinding(learningModel.session);
            return learningModel;
        }
        public async Task<Output> EvaluateAsync(Input input)
        {
            binding.Bind("input", input.input);
            var result = await session.EvaluateAsync(binding, "0");
            var output = new Output();
            output.scores = result.Outputs["scores"] as TensorFloat;
            output.boxes = result.Outputs["boxes"] as TensorFloat;
            return output;
        }
    }
}

