// This file was automatically generated by VS extension Windows Machine Learning Code Generator v3
// from model file landmark_detection_56_se_external.onnx
// Warning: This file may get overwritten if you add add an onnx file with the same name
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Windows.Media;
using Windows.Storage;
using Windows.Storage.Streams;
using Windows.AI.MachineLearning;
namespace FaceRecognitionUWP
{
    
    public sealed class landmark_detection_56_se_externalInput
    {
        public TensorFloat input; // shape(-1,3,56,56)
    }
    
    public sealed class landmark_detection_56_se_externalOutput
    {
        public TensorFloat output; // shape(-1,136)
    }
    
    public sealed class landmark_detection_56_se_externalModel
    {
        private LearningModel model;
        private LearningModelSession session;
        private LearningModelBinding binding;
        public static async Task<landmark_detection_56_se_externalModel> CreateFromStreamAsync(IRandomAccessStreamReference stream)
        {
            landmark_detection_56_se_externalModel learningModel = new landmark_detection_56_se_externalModel();
            learningModel.model = await LearningModel.LoadFromStreamAsync(stream);
            learningModel.session = new LearningModelSession(learningModel.model);
            learningModel.binding = new LearningModelBinding(learningModel.session);
            return learningModel;
        }
        public async Task<landmark_detection_56_se_externalOutput> EvaluateAsync(landmark_detection_56_se_externalInput input)
        {
            binding.Bind("input", input.input);
            var result = await session.EvaluateAsync(binding, "0");
            var output = new landmark_detection_56_se_externalOutput();
            output.output = result.Outputs["output"] as TensorFloat;
            return output;
        }
    }
}

